export const PACIENTE_LIST_REQUEST = 'PACIENTE_LIST_LOADING';
export const PACIENTE_LIST_SUCESS = 'PACIENTE_LIST_SUCESS';
export const PACIENTE_LIST_FAIL = 'PACIENTE_LIST_FAIL';

export const AGENDAMENTO_LIST_REQUEST = 'AGENDAMENTO_LIST_LOADING';
export const AGENDAMENTO_LIST_SUCESS = 'AGENDAMENTO_LIST_SUCESS';
export const AGENDAMENTO_LIST_FAIL = 'AGENDAMENTO_LIST_FAIL';

export const AGENDAMENTO_MODAL_REQUEST = 'AGENDAMENTO_MODAL_LOADING';
export const AGENDAMENTO_MODAL_SUCESS = 'AGENDAMENTO_MODAL_SUCESS';
export const AGENDAMENTO_MODAL_FAIL = 'AGENDAMENTO_MODAL_FAIL';

export const PACIENTE_DETAIL_REQUEST = 'PACIENTE_DETAIL_LOADING';
export const PACIENTE_DETAIL_SUCESS = 'PACIENTE_DETAIL_SUCESS';
export const PACIENTE_DETAIL_FAIL = 'PACIENTE_DETAIL_FAIL';

export const PACIENTE_MODAL_DETALHE_REQUEST = 'PACIENTE_MODAL_DETALHE_LOADING'
export const PACIENTE_MODAL_DETALHE_SUCCESS = 'PACIENTE_MODAL_DETALHE_SUCCESS'
export const PACIENTE_MODAL_DETALHE_FAIL = 'PACIENTE_MODAL_DETALHE_FAIL'

export const NOVO_PACIENTE_REQUEST = 'NOVO_PACIENTE__LOADING'
export const NOVO_PACIENTE_SUCCESS = 'NOVO_PACIENTE_SUCCESS'
export const NOVO_PACIENTE_FAIL = 'NOVO_PACIENTE_FAIL'

export const EDITAR_PACIENTE_REQUEST = 'EDITAR_PACIENTE_LOADING'
export const EDITAR_PACIENTE_SUCCESS = 'EDITAR_PACIENTE_SUCCESS'
export const EDITAR_PACIENTE_FAIL = 'EDITAR_PACIENTE_FAIL'

export const DELETAR_PACIENTE_REQUEST = 'DELETAR_PACIENTE_LOADING'
export const DELETAR_PACIENTE_SUCCESS = 'DELETAR_PACIENTE_SUCCESS'
export const DELETAR_PACIENTE_FAIL = 'DELETAR_PACIENTE_FAIL'

export const DETALHE_AGENDAMENTO_REQUEST = 'DETALHE_AGENDAMENTO_LOADING'
export const DETALHE_AGENDAMENTO_SUCCESS = 'DETALHE_AGENDAMENTO_SUCCESS'
export const DETALHE_AGENDAMENTO_FAIL = 'DETALHE_AGENDAMENTO_FAIL'

export const EDITAR_DETALHE_AGENDAMENTO_REQUEST = 'EDITAR_DETALHE_AGENDAMENTO_LOADING'
export const EDITAR_DETALHE_AGENDAMENTO_SUCCESS = 'EDITAR_DETALHE_AGENDAMENTO_SUCCESS'
export const EDITAR_DETALHE_AGENDAMENTO_FAIL = 'EDITAR_DETALHE_AGENDAMENTO_FAIL'

export const DELETAR_AGENDAMENTO_REQUEST = 'DELETAR_AGENDAMENTO_LOADING'
export const DELETAR_AGENDAMENTO_SUCCESS = 'DELETAR_AGENDAMENTO_SUCCESS'
export const DELETAR_AGENDAMENTO_FAIL = 'DELETAR_AGENDAMENTO_FAIL'
